name: Python application

on:
  push:
    branches: [ "main", "prod" ]
  pull_request:
    branches: [ "main", "prod" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        uv python install 3.14

    - name: Install dependencies
      run: |
        uv sync

    - name: Lint and type-check
      run: |
        uv run mypy .
        uv run ruff check .

    - name: Run tests
      run: |
        uv run pytest .

    - name: Check code formatting
      run: |
        uv run ruff format --check .
